In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import math

import matplotlib.pyplot as plt

In [8]:
# Function to calculate the probabilities that total 1
def softmax(scores):
    exp_scores = np.exp(scores)
    probabilities = exp_scores / np.sum(exp_scores)
    return probabilities

In [77]:
softmax([1,2,3])

array([0.09003057, 0.24472847, 0.66524096])

In [76]:
softmax([1,1,1])

array([0.33333333, 0.33333333, 0.33333333])

In [73]:
# Function to calculate the probabilities and Mean Squared Error
def single_neuron_model(features,labels,weights,bias):
    weighted_sums = np.multiply(features,weights)
    biased_sums = []
    for rows in weighted_sums:
        biased_sums.append(np.sum(rows) + bias)
    biased_sums = np.array(biased_sums)
    probabilities = 1 / (1+np.exp(-biased_sums))
    mse =np.sum(np.square(labels-probabilities)) / len(features)
    
    return probabilities.round(4),mse.round(4)

In [74]:
features = [[0.5,1.0],[-1.5,-2],[2,1.5]]
labels = [0,1,0]
weights = [0.7,-0.4]
bias=-0.1
single_neuron_model(features,labels,weights,bias)

(array([0.4626, 0.4134, 0.6682]), 0.3349)

In [75]:
new_features=[[1,2],[2,3],[3,1]]
new_labels = [1,0,1]
new_weights = [0.5,-0.2]
new_bias = 0
single_neuron_model(new_features,new_labels,new_weights,new_bias)

(array([0.525 , 0.5987, 0.7858]), 0.21)

In [112]:
def precision(y_true,y_pred):
    tp = 0
    fp = 0
    for true,pred in zip(y_true,y_pred):
        if true ==1 and pred ==1:
            tp+=1
        elif true==0 and pred==1:
            fp+=1   
    return tp / (tp+fp)

In [113]:
y_true = np.array([1,0,1,1,0,1])
y_pred=np.array([1,0,1,0,0,1])
result = precision(y_true,y_pred)
print(result)

1.0


In [114]:
y_true_new = np.array([1,0,1,1,0,0])
y_pred_new = np.array([1,0,0,0,0,1])
print(precision(y_true_new,y_pred_new))

0.5
